package io.github.newlunarfire.openapi;

public class Constants {
	public final static String OPENAPIDOCLET_JAVAWSRS_PACKAGE = "javax.ws.rs";
	
	public final static String OPENAPIDOCLET_GET_ANNOTATION = OPENAPIDOCLET_JAVAWSRS_PACKAGE + ".GET";
	public final static String OPENAPIDOCLET_POST_ANNOTATION = OPENAPIDOCLET_JAVAWSRS_PACKAGE + ".POST";
	public final static String OPENAPIDOCLET_PUT_ANNOTATION = OPENAPIDOCLET_JAVAWSRS_PACKAGE + ".PUT";
	public final static String OPENAPIDOCLET_PATCH_ANNOTATION = OPENAPIDOCLET_JAVAWSRS_PACKAGE + ".PATCH";
	public final static String OPENAPIDOCLET_DELETE_ANNOTATION = OPENAPIDOCLET_JAVAWSRS_PACKAGE + ".DELETE";
	public final static String OPENAPIDOCLET_PATH_ANNOTATION = OPENAPIDOCLET_JAVAWSRS_PACKAGE + ".Path";
	public final static String OPENAPIDOCLET_PRODUCES_ANNOTATION = OPENAPIDOCLET_JAVAWSRS_PACKAGE + ".Produces";
	public final static String OPENAPIDOCLET_CONSUMES_ANNOTATION = OPENAPIDOCLET_JAVAWSRS_PACKAGE + ".Consumes";
	public final static String OPENAPIDOCLET_PATHPARAM_ANNOTATION = OPENAPIDOCLET_JAVAWSRS_PACKAGE + ".PathParam";
	
	public final static String[] OPENAPIDOCLET_METHOD_VERB_ANNOTATIONS = {OPENAPIDOCLET_GET_ANNOTATION, OPENAPIDOCLET_POST_ANNOTATION, OPENAPIDOCLET_PUT_ANNOTATION, OPENAPIDOCLET_PATCH_ANNOTATION, OPENAPIDOCLET_DELETE_ANNOTATION};
	public final static String[] OPENAPIDOCLET_METHOD_VERBS = {"GET", "POST", "PUT", "PATCH", "DELETE"};
}
